blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/desreid/skills-expand-your-team-with-copilot/tree/main/docs
    about: View the development and user documentation
